#!/usr/local/bin/python3
import sys

sys.path.append('../')

from Classes.Vector import Vector

# Subject tests:
print("Subject tests:")
u = Vector([0., 0., 0.])
print(u.norm_1(), u.norm(), u.norm_inf())
u = Vector([1., 2., 3.])
print(u.norm_1(), u.norm(), u.norm_inf())
u = Vector([-1., -2.])
print(u.norm_1(), u.norm(), u.norm_inf())

# Corrections tests:
print("Correction tests:")

print("Euclidean norm:")
u = Vector([0])
print(u.norm())
u = Vector([1])
print(u.norm())
u = Vector([0, 0])
print(u.norm())
u = Vector([1, 0])
print(u.norm())
u = Vector([2, 1])
print(u.norm())
u = Vector([4, 2])
print(u.norm())
u = Vector([-4, -2])
print(u.norm())

print("Manhattan norm:")
u = Vector([0])
print(u.norm_1())
u = Vector([1])
print(u.norm_1())
u = Vector([0, 0])
print(u.norm_1())
u = Vector([1, 0])
print(u.norm_1())
u = Vector([2, 1])
print(u.norm_1())
u = Vector([4, 2])
print(u.norm_1())
u = Vector([-4, -2])
print(u.norm_1())

print("Supremum norm:")
u = Vector([0])
print(u.norm_inf())
u = Vector([1])
print(u.norm_inf())
u = Vector([0, 0])
print(u.norm_inf())
u = Vector([1, 0])
print(u.norm_inf())
u = Vector([2, 1])
print(u.norm_inf())
u = Vector([4, 2])
print(u.norm_inf())
u = Vector([-4, -2])
print(u.norm_inf())